name: "Snyk Security SARIF Upload"
on: 
  pull_request:
    types: [opened, synchronize]

jobs:
  snyk-sarif:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Snyk CLI
        run: npm install -g snyk
      
      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
      
      - name: Run Snyk Code
        run: snyk code test --sarif-file-output=snyk-code.sarif || true
      
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: snyk-code.sarif
